### ISSUE TITLE
Still getting old version

### ISSUE THREAD

**Issue by xivk** [oSoc18/bike4brussels#20]
I have the issue of still getting a very old version of the route planner when loading it and others are also having this issue. I think it's related to the service working or something hanging around.

We have logged an issue on the anyways-side of things:

https://github.com/anyways-open/genk-cycling-frontend/issues/8

@jbelien @Fizz55  Any thoughts on this? Any feedback is highly appreciated.

**Comment by Fizz55** [comment]
I think updating this line should fix this. (see comment above the line)
https://github.com/oSoc18/bike4brussels/blob/84d3dc5e89532143f2d555f84086319a3bb2185b/service-worker.js#L17

**Comment by Fizz55** [comment]
The way this works is that when it installs the service worker (by default on first page load) it actually downloads all the html, js and css files to the local cache. When you reload your page, files are served from the cache. If you want to change something to the source files, you have to tell the browser to update the cache. This is done by changing the "version" of the most recent cache. Changing the constant value PRECACHE to something like "precache-v2" should make the clients rebuild their caches until the latest version is changed again.

**Comment by xivk** [comment]
Awesome @Fizz55, thanks for your message, this saves us a *lot* of time! :+1: 

Testing this now!

**Comment by Fizz55** [comment]
@xivk You're welcome! 
hope it works!

**Comment by jbelien** [comment]
Maybe using a date instead of a "version number" would be more convenient, something like `precache-20181213`.

**Comment by xivk** [comment]
Good idea, I think we can close this issue now! Thanks y'all!

**Comment by Fizz55** [comment]
Have you tried renaming the runtime cache also?
https://github.com/oSoc18/bike4brussels/blob/84d3dc5e89532143f2d555f84086319a3bb2185b/service-worker.js#L18
These icons that are still in yellow are not pre-cached (only the files in the PRECACHE_URLS array are added to this cache). These are instead cached on first use and are therefore added to the runtime cache. Only renamed caches get rebuilt, so the runtime cache would still contain the yellow icons.
(The icons should also be added to the PRECACHE_URLS array since every visitor will have to load them anyway, but renaming the runtime cache should display the new icons)

**Comment by jbelien** [comment]
We **finally** got rid of that nasty service worker (see 72683876dfb74f725ab69b544291c10469fa7ea4).
It should fix this issue!

**Comment by Fizz55** [comment]
You know, it's not a fix if it kills a bunch of other features. Not having a Service Worker means not being a PWA, so no adding to homescreen and no fancy app-like splash screen.

**Comment by jbelien** [comment]
In this case, I really don't see the added value to have that Service Worker (and/or being a Progressive Web App).
It's more a liability than a "bunch of other features"!
